language: python

python:
  - 2.7

services:
 - sqlite3
 - rabbitmq

env:
  global:
  - DJANGO_SETTINGS_MODULE="checkout.settings"
  - PYTHONPATH="/home/travis/build/ndarville/checkout-test"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - python manage.py migrate --noinput
  - coverage run --source=core manage.py test core

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls
- echo Code complexity scores:; radon cc --min B ../checkout-test

notifications:
  email: false
